const loaded=Learning.load(localStorage);let state=loaded.state;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selectedChapter=null;
function notice(message){$('storageNotice').textContent=message;$('storageNotice').classList.remove('hidden');}
if(loaded.notice)notice(loaded.notice);
function save(){if(!Learning.persist(localStorage,state))notice('当前浏览器无法保存进度。请下载备份，避免关闭页面后丢失。');$('homeFood').textContent=state.food+' 颗星星';if($('pet').classList.contains('active'))renderPet();}
function activeChapters(subject=state.subject){return catalog.chapters.filter(c=>c.subject===subject&&(subject!=='en'||c.enEdition===state.enEdition));}
function activeSkills(){let ids=new Set(['zh','math','en'].flatMap(s=>activeChapters(s)).map(c=>c.id));return Object.values(catalog.skills).filter(k=>ids.has(k.chapter));}
function switchView(view){document.querySelectorAll('.view,.tab').forEach(x=>x.classList.remove('active'));$(view).classList.add('active');document.querySelector(`[data-view="${view}"]`).classList.add('active');if(view==='home')renderHome();if(view==='exam')renderExam();if(view==='mistakes')renderMistakes();if(view==='report')renderReport();if(view==='pet')renderPet();window.scrollTo(0,0);}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function selectSubject(s){state.subject=s;selectedChapter=null;save();renderHome();}
function selectEdition(v){state.enEdition=v;selectedChapter=null;save();renderHome();}
function renderHome(){let chapters=activeChapters();$('subjects').innerHTML=Object.entries(catalog.subjects).map(([id,label])=>`<button class="${state.subject===id?'primary':''}" onclick="selectSubject('${id}')">${label}</button>`).join('');$('edition').textContent=chapters[0]?.edition||'';$('editionControls').innerHTML=state.subject==='en'?`<label>与孩子课本一致的目录：<select id="enEdition" onchange="selectEdition(this.value)"><option value="units" ${state.enEdition==='units'?'selected':''}>Welcome to school / Unit 1</option><option value="modules" ${state.enEdition==='modules'?'selected':''}>Module 1 — I'm Sam.</option></select></label>`:'';$('resume').innerHTML=state.session&&!state.session.finished?'<button class="primary" onclick="switchView(\'exam\')">继续上次练习（已保存）</button>':'';$('chapters').innerHTML=chapters.map(c=>{let ks=Object.values(catalog.skills).filter(k=>k.chapter===c.id);return `<article class="card chapter"><h3>${esc(c.title)}</h3><p class="muted">${esc(c.lessons)}</p>${ks.map(k=>{let t=Learning.stats(state,k.id);return `<div class="skill"><b>${esc(k.title)}</b> <span class="tag">${t.level}</span><small> ${t.rate===null?'未作答':t.rate+'% · '+t.n+'次作答'}</small><br><button onclick="showLesson('${k.id}')">学重点</button><button onclick="startSkill('${k.id}','practice')">练一练</button>${t.pending||t.level==='薄弱'?`<button onclick="startSkill('${k.id}','reinforce')">强化薄弱点</button>`:''}</div>`;}).join('')}<button onclick="startChapter('${c.id}')">本章小测</button></article>`;}).join('');$('lesson').classList.add('hidden');}
function showLesson(id){let k=catalog.skills[id];$('lesson').classList.remove('hidden');$('lesson').innerHTML=`<h2>${esc(k.title)}</h2><p>${esc(k.learn)}</p><div class="feedback"><b>一起看例子</b><p>${esc(k.example)}</p></div><p class="hint">容易出错：${esc(k.tip)}</p><button class="primary" onclick="startSkill('${id}','practice')">我读懂了，练一练</button>`;state.learned[id]=Date.now();save();$('lesson').scrollIntoView({behavior:'smooth',block:'start'});}
function replaceSession(action){if(state.session&&!state.session.finished){if(!confirm('已有练习尚未结束。开始新练习会结束当前这一组，已答题记录会保留。'))return;}action();save();switchView('exam');}
function startSkill(id,kind='practice'){let pool=catalog.questions.filter(q=>q.skill===id);replaceSession(()=>Learning.begin(state,Learning.pick(state,pool,kind==='retest'?2:5),kind,{skill:id}));}
function startChapter(id){let ks=Object.values(catalog.skills).filter(k=>k.chapter===id);let qs=ks.flatMap(k=>Learning.pick(state,catalog.questions.filter(q=>q.skill===k.id),4));replaceSession(()=>Learning.begin(state,Learning.shuffle(qs),'chapter',{chapter:id}));}
function startReview(qid){replaceSession(()=>{try{Learning.review(state,catalog.questions,qid);}catch(e){notice(e.message);}});}
function renderExam(){let x=state.session;if(!x){$('examBox').innerHTML='<h2>准备好了吗？</h2><p>请先选择一科和一个知识点。</p><button onclick="switchView(\'home\')">选择学习内容</button>';return;}if(x.finished){let weak=[...new Set(x.answers.filter(a=>!a.ok).map(a=>a.skill))];$('examBox').innerHTML=`<h2>${x.score}分 · ${x.passed?'这一组全对啦！':'找到不会的，就是进步的开始'}</h2><p>${x.reward?'获得3颗星星，可以去投喂伙伴。':'看看解析，再试一次。'}</p>${x.kind==='review'?`<p class="feedback">${x.passed?'原题、3道变式和2道复测全部通过，这道错题已巩固。':'本次尚未全部答对，原错题继续保留在待巩固列表。'}</p>`:''}${weak.map(id=>`<button onclick="startSkill('${id}','reinforce')">强化：${esc(catalog.skills[id].title)}</button>`).join('')}<div class="actions"><button onclick="switchView('mistakes')">重做错题</button>${x.skill&&x.kind!=='review'?`<button onclick="startSkill('${x.skill}','retest')">用新题复测</button>`:''}<button onclick="switchView('report')">查看详细报告</button><button onclick="switchView('home')">返回学习</button></div>`;return;}
 let e=x.questions[x.index],q=catalog.questions.find(q=>q.id===e.qid);if(!q){notice('题库已更新，原练习无法继续；已答记录仍保留。');state.session=null;save();renderExam();return;}let k=catalog.skills[q.skill],c=catalog.chapters.find(c=>c.id===q.chapter),a=x.answers[x.index];
 $('examBox').innerHTML=`<div class="examtop"><span class="tag">${esc(catalog.subjects[q.subject])} · ${esc(c.title)}</span><b>${x.index+1} / ${x.questions.length}</b></div><div class="progress-line"><i style="width:${100*x.index/x.questions.length}%"></i></div><p>${esc(k.title)}</p>${x.kind==='review'?`<div class="stages">${['原题重做','3道同类变式','2道复测'].map((t,i)=>`<span class="stage ${i===(x.index===0?0:x.index<=3?1:2)?'current':''}">${t}</span>`).join('')}</div><b>${esc(e.stage)}</b>`:''}<div class="question">${esc(q.prompt)}</div>${e.options?`<div class="options">${e.options.map((o,i)=>`<button class="option ${a?(o===q.answer?'correct':o===a.value?'wrong':''):''}" onclick="answerOption(${i})" ${a?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join('')}</div>`:`<form id="answerForm"><label for="typed">${q.subject==='math'?'填写数值，单位见题目':'填写答案'}</label><input id="typed" autocomplete="off" inputmode="${q.subject==='math'?'decimal':'text'}" value="${esc(a?.value||e.draft||'')}" ${a?'disabled':''}><button class="primary" ${a?'disabled':''}>提交答案</button></form>`}${a?`<div class="feedback" role="status"><b>${a.ok?'答对了，真棒！':'再想一想，你会有进步的'}</b><p>参考答案：${esc(q.answer)}</p><p>${esc(q.explanation)}</p></div><button id="next" class="primary" onclick="nextQuestion()">${x.index===x.questions.length-1?'查看结果':'下一题'}</button>`:`<details><summary>忘记方法了？看看重点</summary><p>${esc(k.learn)}</p><p>${esc(k.example)}</p></details>`}`;
 if($('answerForm')){$('answerForm').onsubmit=event=>{event.preventDefault();answer($('typed').value);};if(!a)$('typed').oninput=()=>{e.draft=$('typed').value;save();};}}
function answerOption(i){let e=state.session.questions[state.session.index];answer(e.options[i]);}
function answer(value){if(!String(value||'').trim()){if($('typed'))$('typed').focus();return;}let r=Learning.submit(state,catalog.questions,value);if(r){save();renderExam();}}
function nextQuestion(){if(Learning.next(state)){save();renderExam();}}
function renderMistakes(){let valid=new Set(activeSkills().map(k=>k.id)),rows=Object.values(state.wrong).filter(w=>valid.has(w.skill)),pending=rows.filter(w=>!w.mastered);$('mistakeStats').innerHTML=`<div class="stat">${rows.length} 道错题</div><div class="stat">${pending.length} 待巩固</div><div class="stat">${rows.length-pending.length} 已巩固</div>`;$('mistakeList').innerHTML=rows.length?rows.sort((a,b)=>Number(a.mastered)-Number(b.mastered)||b.at-a.at).map(w=>{let q=catalog.questions.find(q=>q.id===w.qid);return `<article class="mistake"><span class="tag">${w.mastered?'已巩固':'待巩固'} · ${esc(catalog.subjects[q.subject])} · ${esc(catalog.skills[q.skill].title)}</span><p class="question">${esc(q.prompt)}</p><p>上次作答：${esc(w.value)} · 累计答错 ${w.count} 次</p><details><summary>查看方法与解析</summary><p>${esc(catalog.skills[q.skill].learn)}</p><p>参考答案：${esc(q.answer)}。${esc(q.explanation)}</p></details><button class="primary" onclick="startReview('${q.id}')">重做 → 3道变式 → 复测</button></article>`;}).join(''):'<p class="feedback">当前教材还没有错题。去练一练吧！</p>';$('legacyList').innerHTML=Array.isArray(state.legacy?.wrong)?state.legacy.wrong.map(w=>`<p>${esc(w.q)}<br>原记录答案：${esc(w.a)}（未纳入新版诊断）</p>`).join(''):'暂无旧版错题。';}
function reportRows(){return activeSkills().map(k=>{let c=catalog.chapters.find(c=>c.id===k.chapter),t=Learning.stats(state,k.id);let advice=t.level==='未测试'?'先学重点，再做5道练习':t.level==='样本不足'?'再做不同题，积累至少5道诊断样本':t.pending?'先看方法，再完成错题重做、变式和复测':t.level==='已掌握'?'隔天用新题再测，保持掌握':'针对最近出错的方法进行强化';return {subject:catalog.subjects[c.subject],chapter:c.title,skill:k.title,id:k.id,...t,advice};});}
function reportHTML(){let rows=reportRows();return Object.values(catalog.subjects).map(sub=>{let sr=rows.filter(r=>r.subject===sub),n=sr.reduce((a,r)=>a+r.n,0),c=sr.reduce((a,r)=>a+r.c,0);return `<h3 class="subject-summary">${sub} · ${n?Math.round(100*c/n)+'%':'未测试'} · ${c}/${n} 次答对</h3>${[...new Set(sr.map(r=>r.chapter))].map(ch=>{let cr=sr.filter(r=>r.chapter===ch),cn=cr.reduce((a,r)=>a+r.n,0),cc=cr.reduce((a,r)=>a+r.c,0);return `<h4>${esc(ch)} · ${cn?Math.round(100*cc/cn)+'%':'未测试'}</h4><div class="table-scroll"><table><thead><tr><th>知识点</th><th>答对/作答</th><th>正确率</th><th>最近8次</th><th>不同题</th><th>状态</th><th>建议</th></tr></thead><tbody>${cr.map(r=>`<tr><td>${esc(r.skill)}</td><td>${r.c}/${r.n}</td><td>${r.rate??'—'}${r.rate===null?'':'%'}</td><td>${r.recentRate??'—'}${r.recentRate===null?'':'%'}</td><td>${r.distinct}</td><td>${r.level}${r.pending?' · '+r.pending+'道待巩固':''}</td><td>${r.advice}</td></tr>`).join('')}</tbody></table></div>`;}).join('')}`;}).join('');}
function renderReport(){let rows=reportRows(),n=rows.reduce((a,r)=>a+r.n,0),c=rows.reduce((a,r)=>a+r.c,0);$('reportSummary').innerHTML=`<div class="stat"><div class="big">${n?Math.round(100*c/n)+'%':'—'}</div>总正确率</div><div class="stat"><div class="big">${rows.filter(r=>r.level==='已掌握').length}</div>已掌握知识点</div><div class="stat"><div class="big">${rows.filter(r=>r.pending||r.level==='薄弱').length}</div>待强化知识点</div>`;$('reportTable').innerHTML=reportHTML();}
function download(c,n,t){let url=URL.createObjectURL(new Blob([c],{type:t})),a=document.createElement('a');a.href=url;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function downloadReport(type){let rows=reportRows();if(type==='csv'){let data=[['学科','章节','知识点','答对','作答','正确率','最近8次正确率','不同题数','待巩固错题','状态','建议'],...rows.map(r=>[r.subject,r.chapter,r.skill,r.c,r.n,r.rate===null?'未测试':r.rate+'%',r.recentRate===null?'未测试':r.recentRate+'%',r.distinct,r.pending,r.level,r.advice])];download('\ufeff'+data.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'三年级语数英学习报告.csv','text/csv;charset=utf-8');}else download('<!doctype html><meta charset="utf-8"><title>三年级学习报告</title><style>body{font:16px system-ui;margin:24px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #bbb;padding:6px}h4{break-after:avoid}tr{break-inside:avoid}@media print{button{display:none}}</style><h1>三年级语数英学习报告</h1><p>'+esc(new Date().toLocaleString())+'</p><p>正确率按作答次数加权；至少5道不同题，最近8次正确率达到80%，且没有待巩固错题时显示已掌握。</p>'+reportHTML()+'<button onclick="print()">打印 / 保存PDF</button>','三年级语数英学习报告.html','text/html');}
function exportBackup(){download(JSON.stringify(state,null,2),'三年级学习记录备份.json','application/json');}
save();renderHome();if(state.session&&!state.session.finished)switchView('exam');
