const fs=require('fs');
const old=fs.readFileSync(__dirname+'/original.html','utf8');
let head=old.slice(0,old.indexOf('<header'));
let pet=old.slice(old.indexOf('<section id="pet"'),old.indexOf('<section id="map"'));
let petJS=old.slice(old.indexOf('const petData='),old.indexOf('function topicBar'));
fs.writeFileSync(__dirname+'/pets.js',petJS);
let data=fs.readFileSync(__dirname+'/curriculum.js','utf8');
const zh=require('./zh-data.cjs');
data+='\nconst zhUnits='+JSON.stringify(zh)+';\n';
data+=`zhUnits.forEach((u,i)=>{let ch='z'+(i+1),w=ch+'-sound',r=ch+'-reading';chapter('zh',ch,'第'+(i+1)+'单元 · '+u[0],u[1],'部编版三上 · 修订版（含犟龟）');skill(ch,w,'本单元字音',u[2].split('|').join('；'),'把生字放回词语、句子中朗读。','看清声母、韵母和声调。');skill(ch,r,u[3],u[4],u[5],u[6]);let words=u[2].split('|').map(x=>x.split(':'));words.forEach((x,j)=>item(w,'“'+x[0]+'”的正确读音是？',x[1],[1,2,3].map(k=>words[(j+k)%words.length][1]),'“'+x[0]+'”读'+x[1]+'。'));u[7].forEach(x=>item(r,x[0],x[1],x[2].split('|'),x[3]));});\n`;
fs.writeFileSync(__dirname+'/data.js',data);
const writing=require('./writing-data.cjs');
data+='\nconst poetryUnits='+JSON.stringify(require('./poetry.cjs'))+';\n';
data+=`poetryUnits.forEach(u=>{let id=u[0]+'-poetry';skill(u[0],id,u[1],u[2],u[3],'先背诵，再结合诗句理解，别只记选项位置。');u[4].forEach(x=>item(id,x[0],x[1],x[2].split('|'),x[3]));});\n`;
const scenarios=require('./english-scenarios.cjs');
data+='\nconst revisedScenarios='+JSON.stringify(scenarios)+';\n';
data+=`for(const units of [legacyEn,newEn]){for(const u of units){let p=revisedScenarios[u[3]];if(!p)continue;let chapters=catalog.chapters.filter(c=>c.subject==='en'&&c.title===u[0]);for(const ch of chapters){let id=ch.id+'-sentences';catalog.questions=catalog.questions.filter(q=>q.skill!==id);p.forEach(x=>item(id,x[0],x[1],x[2].split('|'),catalog.skills[id].learn));}}}\n`;
data+='\nconst writingUnits='+JSON.stringify(writing)+';\n';
data+=`writingUnits.forEach((u,i)=>{let id='z'+(i+1)+'-writing';skill('z'+(i+1),id,u[0],u[1],u[2],'先想清楚再表达，写完检查错别字和标点。');u[3].forEach(x=>item(id,x[0],x[1],x[2].split('|'),u[1]));});\n`;
fs.writeFileSync(__dirname+'/data.js',data);
const body=fs.readFileSync(__dirname+'/shell.html','utf8').replace('<!--PET-->',pet);
data+='\n'+fs.readFileSync(__dirname+'/supplement.js','utf8');
fs.writeFileSync(__dirname+'/data.js',data);
fs.writeFileSync(__dirname+'/index.html',head+body.replace('src="curriculum.js?v=3"','src="data.js?v=3"').replaceAll('?v=3','?v=20260923'));
