/* Pure learning state machine, also exercised by node tests. */
const Learning=(()=>{
 const KEY='grade3LearningV3';
 function fresh(){return {version:3,subject:'zh',enEdition:'units',history:[],wrong:{},learned:{},session:null,food:0,answered:0,best:null,reinforceStreak:0,rabbitXp:0,pandaXp:0,turtleXp:0,mantisXp:0,activePet:'rabbit',names:{rabbit:'小团子',panda:'圆滚滚',turtle:'慢慢',mantis:'小刀'},legacy:null};}
 function load(storage){let s=fresh(),notice='';try{let raw=storage.getItem(KEY);if(raw){let v=JSON.parse(raw);if(v.version!==3||!Array.isArray(v.history)||!v.wrong||typeof v.wrong!=='object'||Array.isArray(v.wrong))throw Error('格式不正确');s={...s,...v,names:{...s.names,...v.names}};}else{let old=storage.getItem('grade3LangState');if(old){let v=JSON.parse(old);s.legacy=v;['food','rabbitXp','pandaXp','turtleXp','mantisXp'].forEach(k=>{if(Number.isFinite(v[k])&&v[k]>=0)s[k]=v[k];});if(['rabbit','panda','turtle','mantis'].includes(v.activePet))s.activePet=v.activePet;if(v.names)s.names={...s.names,...v.names};}}}catch(e){notice='学习记录暂时无法读取，原始记录未删除。请先备份，当前练习仍可进行。';s.readOnly=true;}return {state:s,notice};}
 function persist(storage,s){if(s.readOnly)return false;try{storage.setItem(KEY,JSON.stringify(s));return true;}catch(e){return false;}}
 function shuffle(a,random=Math.random){let b=[...a];for(let i=b.length-1;i>0;i--){let j=Math.floor(random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
 function normalize(v){return String(v).normalize('NFKC').trim().replace(/[‘’]/g,"'").replace(/\s+/g,' ').toLowerCase();}
 function correct(q,v){if(q.options)return String(v)===q.answer;let a=normalize(q.answer),b=normalize(v);if(/^-?\d+(\.\d+)?$/.test(a))return /^-?\d+(\.\d+)?$/.test(b)&&Number(a)===Number(b);return a===b;}
 function stats(s,id){let h=s.history.filter(x=>x.skill===id),recent=h.slice(-8),pending=Object.values(s.wrong).filter(w=>w.skill===id&&!w.mastered).length,distinct=new Set(h.map(x=>x.qid)).size,c=h.filter(x=>x.ok).length,rate=h.length?Math.round(100*c/h.length):null,recentRate=recent.length?Math.round(100*recent.filter(x=>x.ok).length/recent.length):null;let level=!h.length?'未测试':distinct<5?'样本不足':pending?'待巩固':recentRate>=80?'已掌握':recentRate<60?'薄弱':'练习中';return {n:h.length,c,rate,recentRate,distinct,pending,level};}
 function pick(s,pool,n,exclude=[]){let used=new Set(s.history.map(x=>x.qid)),allowed=pool.filter(q=>!exclude.includes(q.id));return [...shuffle(allowed.filter(q=>!used.has(q.id))),...shuffle(allowed.filter(q=>used.has(q.id)))].slice(0,n);}
 function begin(s,qs,kind,meta={}){if(!qs.length)throw Error('这个知识点暂时没有可用题目');let id=Date.now()+'-'+Math.random().toString(36).slice(2);s.session={id,kind,...meta,questions:qs.map((q,i)=>({qid:q.id,stage:meta.stages?.[i]||kind,options:q.options?shuffle(q.options):null})),index:0,answers:[],finished:false};return s.session;}
 function review(s,bank,qid){let w=s.wrong[qid],q=bank.find(q=>q.id===qid);if(!w||!q)throw Error('原题暂不可用，请查看旧版记录');let variants=pick(s,bank.filter(x=>x.skill===q.skill),5,[qid]);if(variants.length<5)throw Error('同知识点变式不足，暂不能确认掌握');return begin(s,[q,...variants],'review',{source:qid,skill:q.skill,stages:['原题重做','同类变式 1/3','同类变式 2/3','同类变式 3/3','复测 1/2','复测 2/2']});}
 function submit(s,bank,value){let session=s.session;if(!session||session.finished||session.answers[session.index])return null;let entry=session.questions[session.index],q=bank.find(x=>x.id===entry.qid);if(!q)throw Error('题目已更新，请返回重新开始');if(!String(value).trim())return null;if(q.options&&!entry.options.includes(value))return null;let ok=correct(q,value),record={qid:q.id,skill:q.skill,chapter:q.chapter,subject:q.subject,ok,value:String(value),at:Date.now(),session:session.id,stage:entry.stage};session.answers[session.index]=record;s.history.push(record);s.answered++;if(!ok){let w=s.wrong[q.id]||{qid:q.id,skill:q.skill,chapter:q.chapter,subject:q.subject,count:0};w.count++;w.value=String(value);w.at=record.at;w.mastered=false;s.wrong[q.id]=w;}s.reinforceStreak=ok?s.reinforceStreak+1:0;return record;}
 function next(s){let x=s.session;if(!x||x.finished||!x.answers[x.index])return false;if(x.index<x.questions.length-1){x.index++;return true;}finish(s);return true;}
 function finish(s){let x=s.session;if(!x||x.finished||x.answers.filter(Boolean).length!==x.questions.length)return false;x.finished=true;x.score=Math.round(100*x.answers.filter(a=>a.ok).length/x.questions.length);x.passed=x.answers.every(a=>a.ok);if(x.kind==='review'&&x.passed){s.wrong[x.source].mastered=true;s.wrong[x.source].masteredAt=Date.now();}if(x.score>=90){s.food+=3;x.reward=3;}s.best=Math.max(s.best||0,x.score);return true;}
 return {KEY,fresh,load,persist,shuffle,normalize,correct,stats,pick,begin,review,submit,next,finish};
})();
if(typeof module!=='undefined')module.exports=Learning;
