const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
(async()=>{let server=http.createServer((req,res)=>{let url=new URL(req.url,'http://localhost'),name=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1)),p=path.resolve(__dirname,name);if(!p.startsWith(__dirname+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html'}[path.extname(p)]||'text/plain')+'; charset=utf-8');res.end(fs.readFileSync(p));}catch(e){res.writeHead(404).end();}}).listen(8766,'127.0.0.1'),b;let results=[],errors=[];
try{
 b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});let c=await b.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:8766/');
 let entries=await p.evaluate(()=>catalog.chapters.map(c=>({id:c.id,subject:c.subject,edition:c.enEdition}))),skillCount=0;
 for(let ch of entries){console.log("Testing chapter",ch.id);await p.getByRole('button',{name:'今日学习',exact:true}).click();await p.getByRole('button',{name:{zh:'语文',math:'数学',en:'英语'}[ch.subject],exact:true}).click();if(ch.subject==='en')await p.locator('#enEdition').selectOption(ch.edition);
 let pos=await p.evaluate(id=>activeChapters().findIndex(c=>c.id===id),ch.id),card=p.locator('.chapter').nth(pos),skills=await card.locator('.skill').count();
 for(let i=0;i<skills;i++){await card.locator('.skill').nth(i).getByRole('button',{name:'学重点',exact:true}).click();assert(await p.locator('#lesson').isVisible());assert((await p.locator('#lesson').innerText()).length>30);skillCount++;}
 await card.getByRole('button',{name:'本章小测',exact:true}).click();assert.equal(await p.evaluate(()=>new Set(state.session.questions.map(e=>catalog.questions.find(q=>q.id===e.qid).chapter)).size),1);assert.equal(await p.evaluate(()=>catalog.questions.find(q=>q.id===state.session.questions[0].qid).chapter),ch.id);let q=await p.evaluate(()=>catalog.questions.find(q=>q.id===state.session.questions[state.session.index].qid));if(q.options){await p.locator('.option').filter({hasText:new RegExp('^'+'.*'+q.answer.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$')}).first().click();}else{await p.locator('#typed').fill(q.answer);await p.getByRole('button',{name:'提交答案',exact:true}).click();}assert(await p.locator('.feedback').count());
 }
 results.push(`全部${entries.length}个教材章节入口/小测、${skillCount}个知识点学习卡`);
 // Real backup round trip through the file input and confirmation dialog.
 await p.getByRole('button',{name:'学习报告',exact:true}).click();let before=await p.evaluate(()=>state.history.length);for(let label of ['下载CSV','下载可打印报告','备份学习记录']){let event=p.waitForEvent('download');await p.getByRole('button',{name:label,exact:true}).click();let d=await event,file=await d.path(),text=fs.readFileSync(file,'utf8');assert(text.length>100);if(label==='备份学习记录'){assert.equal(JSON.parse(text).history.length,before);await p.locator('#backupFile').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(text)});await p.getByText('学习记录恢复成功。',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>state.history.length),before);}}
 await p.locator('#backupFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":3,"history":[null],"wrong":{}}')});await p.getByText('未导入：',{exact:false}).waitFor();assert.equal(await p.evaluate(()=>state.history.length),before);results.push('CSV/打印报告/JSON备份下载、有效备份恢复、拒绝无效备份且保留记录');
 await p.getByRole('button',{name:'成长伙伴',exact:true}).click();for(let id of ['Rabbit','Panda','Turtle','Mantis']){await p.locator('#pick'+id).click();await p.locator('#petNameInput').fill('伙伴'+id[0]);await p.getByRole('button',{name:'保存',exact:true}).click();await p.getByRole('button',{name:'摸摸它',exact:true}).click();await p.getByRole('button',{name:'一起玩',exact:true}).click();assert.equal(await p.locator('#petUnlocks > div').count(),10);}results.push('四种宠物切换、命名、互动、10级图鉴');
 await p.getByRole('button',{name:'今日学习',exact:true}).click();for(let width of [320,390,820,1280]){await p.setViewportSize({width,height:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width);}await p.screenshot({path:__dirname+'/updated-desktop.png',fullPage:true});results.push('320/390手机、820平板、1280桌面宽度无横向溢出');
 // Isolated synthetic records, never the user's browser data.
 for(let raw of ['{bad','null',JSON.stringify({version:3,history:[null],wrong:{}}),JSON.stringify({version:3,history:[],wrong:{},session:{index:7}})]){let isolated=await b.newContext();await isolated.addInitScript(value=>localStorage.setItem('grade3LearningV3',value),raw);let page=await isolated.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8766/');assert.equal(await page.locator('.chapter').count(),8);await page.getByRole('button',{name:'成长伙伴',exact:true}).click();assert(await page.locator('#petEmoji').isVisible());await isolated.close();}
 let disabled=await b.newContext();await disabled.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Denied','SecurityError');}}));let dp=await disabled.newPage();dp.on('pageerror',e=>errors.push(e.message));await dp.goto('http://127.0.0.1:8766/');assert.equal(await dp.locator('.chapter').count(),8);assert(await dp.locator('#storageNotice').isVisible());await disabled.close();results.push('损坏JSON/null/损坏题记录/损坏会话/禁止localStorage均能打开页面');
 assert.deepEqual(errors,[]);results.push('全部测试过程无JavaScript页面错误');fs.writeFileSync(__dirname+'/full-ui-test-results.json',JSON.stringify({passed:results,errors},null,2));console.log(results);
}finally{if(b)await b.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
