const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const ctx=vm.createContext({});vm.runInContext(fs.readFileSync(__dirname+'/data.js','utf8'),ctx);const data=vm.runInContext('catalog',ctx),L=require('./engine.js');
const checks=[];function test(name,fn){fn();checks.push(name);}
test('题库结构、唯一题目、唯一选项及答案',()=>{let ids=new Set(),prompts=new Set();for(let q of data.questions){assert(!ids.has(q.id),q.id);ids.add(q.id);let key=q.chapter+q.prompt;assert(!prompts.has(key),'duplicate '+q.prompt);prompts.add(key);assert(q.answer&&q.explanation&&data.skills[q.skill]);if(q.options){assert.equal(q.options.length,4);assert.equal(new Set(q.options).size,4,q.prompt);assert.equal(q.options.filter(o=>o===q.answer).length,1);}}});
test('每知识点至少6道互异题供原题、3变式、2复测',()=>{for(let k of Object.keys(data.skills))assert(data.questions.filter(q=>q.skill===k).length>=6,k);});
test('数学范围：排除分数、面积、相遇、鸡兔等题',()=>{for(let q of data.questions.filter(q=>q.subject==='math'))assert(!/鸡兔|相遇|追及|面积|分数|平均数|盈亏/.test(q.prompt));});
test('数值和英文规范判分',()=>{assert(L.correct({answer:'3.0',options:null},'3'));assert(!L.correct({answer:'3',options:null},'3abc'));assert(L.correct({answer:'schoolbag',options:null},' Schoolbag '));assert(!L.correct({answer:'head',options:null},'had'));});
test('重复提交不重复统计',()=>{let s=L.fresh(),q=data.questions[0];L.begin(s,[q],'practice');L.submit(s,data.questions,q.answer);assert.equal(L.submit(s,data.questions,q.answer),null);assert.equal(s.history.length,1);L.next(s);assert.equal(s.food,3);L.finish(s);assert.equal(s.food,3);});
test('错题闭环、失败保留、成功解锁、变式互异',()=>{let s=L.fresh(),q=data.questions[0];L.begin(s,[q],'practice');L.submit(s,data.questions,'-99');L.next(s);L.review(s,data.questions,q.id);assert.equal(s.session.questions.length,6);assert.equal(new Set(s.session.questions.map(q=>q.qid)).size,6);for(let i=0;i<6;i++){let qq=data.questions.find(q=>q.id===s.session.questions[s.session.index].qid);L.submit(s,data.questions,i===3?'-99':qq.answer);L.next(s);}assert(!s.wrong[q.id].mastered);L.review(s,data.questions,q.id);for(let i=0;i<6;i++){let qq=data.questions.find(q=>q.id===s.session.questions[s.session.index].qid);L.submit(s,data.questions,qq.answer);L.next(s);}assert(s.wrong[q.id].mastered);assert.equal(s.wrong[q.id].count,1);});
test('刷新保留题目、选项顺序和已答状态',()=>{let s=L.fresh(),q=data.questions.find(q=>q.options);L.begin(s,[q],'practice');L.submit(s,data.questions,q.answer);let mem={};let st={getItem:k=>mem[k]||null,setItem:(k,v)=>mem[k]=v};assert(L.persist(st,s));let r=L.load(st).state;assert.deepEqual(r.session,s.session);assert.equal(L.submit(r,data.questions,q.answer),null);});
test('损坏存储和拒绝存储不崩溃且不覆盖原记录',()=>{let st={getItem:()=>'{bad',setItem:()=>{throw Error('blocked')}};let r=L.load(st);assert(r.notice);assert(r.state.readOnly);assert(!L.persist(st,r.state));assert(!L.persist(st,L.fresh()));});
test('旧版迁移只保留奖励与历史，不伪造新版掌握度',()=>{let old={food:9,mantisXp:21,wrong:[{q:'old'}],stats:{z1:{n:99,c:99}}},st={getItem:k=>k==='grade3LangState'?JSON.stringify(old):null};let r=L.load(st).state;assert.equal(r.food,9);assert.equal(r.mantisXp,21);assert.equal(r.history.length,0);assert.equal(r.legacy.wrong.length,1);});
test('样本不足不判掌握，弱点可随进步恢复',()=>{let s=L.fresh(),qs=data.questions.filter(q=>q.skill==='m1-order');L.begin(s,qs.slice(0,5),'practice');for(let q of qs.slice(0,5)){L.submit(s,data.questions,q.answer);L.next(s);}assert.equal(L.stats(s,'m1-order').level,'已掌握');assert.equal(L.stats(s,'m1-order').rate,100);});
test('选项随机位置覆盖A/B/C/D且不改变答案',()=>{let q=data.questions.find(q=>q.options),seen=new Set();for(let i=0;i<100;i++){let s=L.fresh();L.begin(s,[q],'practice');seen.add(s.session.questions[0].options.indexOf(q.answer));}assert.equal(seen.size,4);});
let result={questions:data.questions.length,skills:Object.keys(data.skills).length,chapters:data.chapters.length,bySubject:Object.fromEntries(['zh','math','en'].map(s=>[s,data.questions.filter(q=>q.subject===s).length])),passed:checks};fs.writeFileSync(__dirname+'/test-results.json',JSON.stringify(result,null,2));console.log(result);
